import json
import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components

# ==========================================
# TIMELINE ENGINE & MULTI-FILE INGESTION LOGIC
# ==========================================

class TimelineCorrelationEngine:
    """
    Ingests and transforms data from .csv and .txt output files generated by
    main_investigation_pipeline.py into chronologically structured timelines.
    """

    EVENT_COLOR_MAP = {
        "Occurrence": "#EF4444",        # Crimson / Incident Occurrence
        "FIR Report": "#F59E0B",        # Amber / Reporting Time
        "Call (CDR)": "#3B82F6",        # Blue / Telecom Voice
        "IPDR Session": "#0284C7",      # Light Blue / Web & Proxy
        "Subscriber Reg": "#06B6D4",    # Cyan / SIM Activation
        "FASTag / Vehicle": "#10B981", # Green / Toll Pass
        "ANPR Scan": "#059669",        # Emerald / Camera Scan
        "Bank Transaction": "#8B5CF6", # Purple / Banking
        "Crypto On-Chain": "#EC4899",  # Pink / Blockchain
        "Crypto KYC/Ramp": "#D946EF",  # Fuchsia / Exchange
        "Anomaly Alert": "#DC2626"      # Red Alert / Fraud & Mismatch
    }

    @classmethod
    def load_pipeline_data(cls) -> Dict[str, Any]:
        """Loads available CSV and TXT files generated by main_investigation_pipeline.py."""
        data = {}

        files_to_load = {
            "fir": "complete_fir_dataset.csv",
            "cdr": "Call_Recording.csv",
            "sdr": "Subscriber_Detail_Records.csv",
            "ipdr": "IP_Detail_Records.csv",
            "fastag": "FASTag_Toll_Logs.csv",
            "anpr": "ANPR_Camera_Feeds.csv",
            "bank": "Bank_Statement_Records.csv",
            "upi": "UPI_Payment_Gateway_Logs.csv",
            "crypto": "Crypto_OnChain_Transactions.csv",
            "crypto_ramp": "Crypto_Exchange_OnOffRamp_Logs.csv"
        }

        for key, filepath in files_to_load.items():
            if os.path.exists(filepath):
                try:
                    data[key] = pd.read_csv(filepath)
                except Exception:
                    data[key] = pd.DataFrame()
            else:
                data[key] = pd.DataFrame()

        data["txt_anomalies"] = cls._parse_text_report("FINAL_GOVERNMENT_CASE_INVESTIGATION_REPORT.txt")
        return data

    @classmethod
    def _parse_text_report(cls, filepath: str) -> List[Dict[str, Any]]:
        """Parses anomalies and findings out of the generated .txt report."""
        if not os.path.exists(filepath):
            return []

        anomalies = []
        current_case = "UNKNOWN"

        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line_str = line.strip()
                if "1. FIR BASIC INFORMATION - CASE ID:" in line_str:
                    match = re.search(r"CASE ID:\s*(FIR/\d+/\d+|\w+)", line_str)
                    if match:
                        current_case = match.group(1)
                elif "SEVERITY:" in line_str:
                    anomalies.append({
                        "Case_ID": current_case,
                        "Details": line_str
                    })
        return anomalies

    @classmethod
    def build_case_timeline(cls, data_store: Dict[str, Any], selected_case_id: Optional[str] = None) -> pd.DataFrame:
        """Builds a combined timeline dataframe mapping events from Occurrence -> FIR Reporting -> Logs."""
        events = []

        # 1. FIR & Occurrence
        fir_df = data_store.get("fir", pd.DataFrame())
        if not fir_df.empty:
            target_fir = fir_df if not selected_case_id else fir_df[fir_df["FIR_No"] == selected_case_id]
            for _, row in target_fir.iterrows():
                case_id = str(row.get("FIR_No", "N/A"))
                place_of_occ = str(row.get("Place_of_Occurrence", "Unknown"))
                ps_location = str(row.get("Police_Station", "Police Station"))

                report_dt_str = str(row.get("Date_Time_of_FIR", ""))
                try:
                    rep_dt = datetime.strptime(report_dt_str, "%Y-%m-%d %H:%M")
                except ValueError:
                    rep_dt = datetime.now()

                days_offset = int(row.get("Days_Offset_N", 0))
                occ_dt = rep_dt - pd.Timedelta(days=days_offset)

                events.append({
                    "Case_ID": case_id, "DateTime": occ_dt, "Date": occ_dt.strftime("%Y-%m-%d"),
                    "Time": occ_dt.strftime("%H:%M"), "Event Type": "Occurrence",
                    "Person": str(row.get("Accused_Name_Alias", "Unknown Accused")), "Location": place_of_occ,
                    "Description": f"Incident Occurrence: {row.get('Case_Type', 'Offense')} reported at {place_of_occ}.",
                    "Source": "FIR Occurrence Log", "Risk Score": 90
                })

                events.append({
                    "Case_ID": case_id, "DateTime": rep_dt, "Date": rep_dt.strftime("%Y-%m-%d"),
                    "Time": rep_dt.strftime("%H:%M"), "Event Type": "FIR Report",
                    "Person": str(row.get("Informant_Name", "Complainant")), "Location": ps_location,
                    "Description": f"FIR Registered at {ps_location} by {row.get('Informant_Name')}. Act: {row.get('Acts_Sections')}",
                    "Source": "FIR Filing Record", "Risk Score": 50
                })

        # 2. Telecom Call Records (CDR)
        cdr_df = data_store.get("cdr", pd.DataFrame())
        if not cdr_df.empty:
            target_cdr = cdr_df if not selected_case_id else cdr_df[cdr_df["Case_ID"] == selected_case_id]
            for _, row in target_cdr.iterrows():
                try:
                    c_dt = datetime.strptime(str(row.get("Call Date & Time")), "%d/%m/%Y %H:%M")
                except Exception:
                    continue

                duration = int(row.get("Duration (s)", 0))
                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": c_dt, "Date": c_dt.strftime("%Y-%m-%d"),
                    "Time": c_dt.strftime("%H:%M"), "Event Type": "Call (CDR)",
                    "Person": str(row.get("Calling Number (A-Party)")), "Location": str(row.get("First Tower Location", "Cell Tower")),
                    "Description": f"Call to {row.get('Called Number (B-Party)')} ({duration}s)",
                    "Source": "CDR Logs", "Risk Score": 85 if duration < 5 else 35
                })

        # 3. Subscriber Registrations (SDR)
        sdr_df = data_store.get("sdr", pd.DataFrame())
        if not sdr_df.empty:
            target_sdr = sdr_df if not selected_case_id else sdr_df[sdr_df["Case_ID"] == selected_case_id]
            for _, row in target_sdr.iterrows():
                act_str = str(row.get("Activation Date & Time", "")).replace(" IST", "")
                try:
                    s_dt = datetime.strptime(act_str, "%d-%b-%Y %H:%M:%S")
                except Exception:
                    continue

                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": s_dt, "Date": s_dt.strftime("%Y-%m-%d"),
                    "Time": s_dt.strftime("%H:%M"), "Event Type": "Subscriber Reg",
                    "Person": str(row.get("Subscriber Name")), "Location": str(row.get("Local Address", "RTO / Telecom Circle")),
                    "Description": f"SIM Activation: {row.get('Mobile Number')} ({row.get('Service Provider / Circle')})",
                    "Source": "SDR Database", "Risk Score": 20
                })

        # 4. Internet Protocol Records (IPDR)
        ipdr_df = data_store.get("ipdr", pd.DataFrame())
        if not ipdr_df.empty:
            target_ipdr = ipdr_df if not selected_case_id else ipdr_df[ipdr_df["Case_ID"] == selected_case_id]
            for _, row in target_ipdr.iterrows():
                try:
                    i_dt = datetime.strptime(str(row.get("Session Start Time")), "%d/%m/%Y %H:%M:%S")
                except Exception:
                    continue

                src_ip = str(row.get("Source Public IP"))
                is_tor = src_ip in ["185.220.101.4", "185.220.101.5", "103.211.54.12"]
                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": i_dt, "Date": i_dt.strftime("%Y-%m-%d"),
                    "Time": i_dt.strftime("%H:%M"), "Event Type": "Anomaly Alert" if is_tor else "IPDR Session",
                    "Person": str(row.get("Allocated Private IP")), "Location": f"Public IP: {src_ip}",
                    "Description": f"Data Session: {row.get('Volume Out (Bytes)')} bytes transferred via {row.get('RAT Type')}",
                    "Source": "IPDR Logs", "Risk Score": 95 if is_tor else 25
                })

        # 5. Vehicle FASTag Toll Passages
        fastag_df = data_store.get("fastag", pd.DataFrame())
        if not fastag_df.empty:
            target_fastag = fastag_df if not selected_case_id else fastag_df[fastag_df["Case_ID"] == selected_case_id]
            for _, row in target_fastag.iterrows():
                try:
                    v_dt = datetime.strptime(str(row.get("Timestamp (IST)")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                is_mismatch = str(row.get("ANPR Cross-Match")) == "MISMATCH"
                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": v_dt, "Date": v_dt.strftime("%Y-%m-%d"),
                    "Time": v_dt.strftime("%H:%M"), "Event Type": "Anomaly Alert" if is_mismatch else "FASTag / Vehicle",
                    "Person": str(row.get("Vehicle Registration")), "Location": str(row.get("Toll Plaza ID & Location")),
                    "Description": f"Vehicle crossed toll plaza. Status: {row.get('Txn Status')}",
                    "Source": "FASTag Feed", "Risk Score": 95 if is_mismatch else 40
                })

        # 6. ANPR Camera Scans
        anpr_df = data_store.get("anpr", pd.DataFrame())
        if not anpr_df.empty:
            target_anpr = anpr_df if not selected_case_id else anpr_df[anpr_df["Case_ID"] == selected_case_id]
            for _, row in target_anpr.iterrows():
                try:
                    a_dt = datetime.strptime(str(row.get("Detection Time")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                flag = str(row.get("Investigation Flag", "PASS"))
                is_alert = flag != "PASS"
                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": a_dt, "Date": a_dt.strftime("%Y-%m-%d"),
                    "Time": a_dt.strftime("%H:%M"), "Event Type": "Anomaly Alert" if is_alert else "ANPR Scan",
                    "Person": str(row.get("Captured Plate")), "Location": str(row.get("Camera ID & Location")),
                    "Description": f"ANPR Scan ({row.get('Vehicle Color & Class')}). Flag: {flag}",
                    "Source": "ANPR Feed", "Risk Score": 90 if is_alert else 30
                })

        # 7. Bank & UPI Transactions
        bank_df = data_store.get("bank", pd.DataFrame())
        if not bank_df.empty:
            target_bank = bank_df if not selected_case_id else bank_df[bank_df["Case_ID"] == selected_case_id]
            for _, row in target_bank.iterrows():
                try:
                    b_dt = datetime.strptime(str(row.get("Transaction_DateTime")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": b_dt, "Date": b_dt.strftime("%Y-%m-%d"),
                    "Time": b_dt.strftime("%H:%M"), "Event Type": "Bank Transaction",
                    "Person": str(row.get("Person")), "Location": "Banking System",
                    "Description": f"{row.get('Type_CR_DR')} Rs.{row.get('Amount_INR')} via {row.get('Channel')} to {row.get('Counterparty_Name')}",
                    "Source": "Bank Statements", "Risk Score": 65
                })

        # 8. Crypto On-Chain Transfers
        crypto_df = data_store.get("crypto", pd.DataFrame())
        if not crypto_df.empty:
            target_crypto = crypto_df if not selected_case_id else crypto_df[crypto_df["Case_ID"] == selected_case_id]
            for _, row in target_crypto.iterrows():
                try:
                    cr_dt = datetime.strptime(str(row.get("Timestamp")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": cr_dt, "Date": cr_dt.strftime("%Y-%m-%d"),
                    "Time": cr_dt.strftime("%H:%M"), "Event Type": "Crypto On-Chain",
                    "Person": str(row.get("Sender_Wallet"))[:10] + "...", "Location": str(row.get("Blockchain")),
                    "Description": f"Transfer: {row.get('Amount')} {row.get('Asset')} to {row.get('Receiver_Wallet')[:10]}...",
                    "Source": "Blockchain Ledger", "Risk Score": 80
                })

        # 9. Crypto On/Off-Ramp Log
        ramp_df = data_store.get("crypto_ramp", pd.DataFrame())
        if not ramp_df.empty:
            target_ramp = ramp_df if not selected_case_id else ramp_df[ramp_df["Case_ID"] == selected_case_id]
            for _, row in target_ramp.iterrows():
                try:
                    rm_dt = datetime.strptime(str(row.get("Timestamp")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                events.append({
                    "Case_ID": str(row.get("Case_ID")), "DateTime": rm_dt, "Date": rm_dt.strftime("%Y-%m-%d"),
                    "Time": rm_dt.strftime("%H:%M"), "Event Type": "Crypto KYC/Ramp",
                    "Person": str(row.get("Account_UID")), "Location": "Exchange Off-Ramp",
                    "Description": f"{row.get('Type')}: {row.get('Amount')} {row.get('Asset')} via {row.get('Channel')}",
                    "Source": "Exchange Ledger", "Risk Score": 85
                })

        if not events:
            return pd.DataFrame()

        df = pd.DataFrame(events)
        df["DateTime"] = pd.to_datetime(df["DateTime"])
        return df.sort_values("DateTime")

# ==========================================
# STREAMLIT UI RENDERER: TIMELINE PAGE
# ==========================================

def render_timeline_page():
    st.markdown("## Multi-Source Case Timeline Analysis")
    st.caption("Extracted automatically from CSV logs and TXT investigation summaries")

    data_store = TimelineCorrelationEngine.load_pipeline_data()
    fir_df = data_store.get("fir", pd.DataFrame())

    if fir_df.empty:
        st.warning("No CSV data found. Please run your data pipeline first.")
        return

    available_cases = ["All Cases"] + list(fir_df["FIR_No"].unique())
    selected_case = st.selectbox("Select Specific Case ID to Inspect:", options=available_cases)

    case_filter = None if selected_case == "All Cases" else selected_case
    timeline_df = TimelineCorrelationEngine.build_case_timeline(data_store, selected_case_id=case_filter)

    if timeline_df.empty:
        st.info("No correlated timeline events available for this selection.")
        return

    st.sidebar.markdown("### Filter Timeline View")
    event_types = list(timeline_df["Event Type"].unique())
    selected_types = st.sidebar.multiselect("Event Types:", options=event_types, default=event_types)

    filtered_df = timeline_df[timeline_df["Event Type"].isin(selected_types)]

    st.subheader("Interactive Multi-Event Chronology Chart")
    fig = px.scatter(
        filtered_df,
        x="DateTime",
        y="Person",
        color="Event Type",
        size="Risk Score",
        hover_data={"Case_ID": True, "Location": True, "Description": True, "Source": True, "Risk Score": True},
        color_discrete_map=TimelineCorrelationEngine.EVENT_COLOR_MAP,
        title=f"Incident Timeline & Sequence ({selected_case})"
    )

    fig.update_traces(marker=dict(symbol="circle", line=dict(width=1, color="DarkSlateGrey")))
    fig.update_layout(
        xaxis_title="Timeline",
        yaxis_title="Entity / Involved Person / Vehicle / Address",
        height=450,
        template="plotly_dark"
    )

    st.plotly_chart(fig, use_container_width=True)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Extracted Events", len(filtered_df))
    c2.metric("Involved Entities", filtered_df["Person"].nunique())
    c3.metric("Primary Location", filtered_df["Location"].mode()[0] if not filtered_df.empty else "N/A")
    c4.metric("Max Risk Score", f"{filtered_df['Risk Score'].max() if not filtered_df.empty else 0}/100")

    st.subheader("Correlated Event Data Table")
    display_df = filtered_df[[
        "Case_ID", "Date", "Time", "Event Type", "Person",
        "Location", "Description", "Source", "Risk Score"
    ]].copy()

    st.dataframe(
        display_df,
        column_config={
            "Risk Score": st.column_config.ProgressColumn(
                "Risk Severity", format="%d", min_value=0, max_value=100
            )
        },
        use_container_width=True,
        hide_index=True
    )

    txt_anomalies = data_store.get("txt_anomalies", [])
    if txt_anomalies:
        st.subheader("Automated Report Intelligence Flags (.txt Summary)")
        relevant_anomalies = [
            a for a in txt_anomalies if case_filter is None or a["Case_ID"] == case_filter
        ]
        if relevant_anomalies:
            for item in relevant_anomalies[:5]:
                st.error(f"**[{item['Case_ID']}]**: {item['Details']}")
        else:
            st.success("No automated report anomalies detected for this case.")

NETWORK_REPORT_PATH = "network_analytics_report.json"
INTELLIGENCE_REPORT_PATH = "intelligence_report.json"
NETWORK_MAP_HTML_PATH = "network_map.html"

def _load_json(path: str) -> Optional[Dict[str, Any]]:
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None

def render_network_intelligence_page():
    st.markdown("## Criminal Network & Intelligence Overview")
    st.caption("Generated by network and intelligence analytics engine")

    net_report = _load_json(NETWORK_REPORT_PATH)
    intel_report = _load_json(INTELLIGENCE_REPORT_PATH)

    if not net_report and not intel_report:
        st.warning("No analysis output found. Please run your network analytics script first.")
        return

    if net_report:
        s = net_report.get("summary", {})
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Entities (Nodes)", s.get("total_nodes", 0))
        c2.metric("Relationships (Edges)", s.get("total_edges", 0))
        c3.metric("Critical Bridges", s.get("critical_bridge_count", 0))
        c4.metric("Cells / Communities", s.get("community_count", 0))

    if intel_report:
        m = intel_report.get("meta", {})
        c1, c2 = st.columns(2)
        c1.metric("Intelligence Alerts", m.get("alert_count", 0))
        c2.metric("Critical / High Severity", m.get("critical_or_high_alerts", 0))

    if os.path.exists(NETWORK_MAP_HTML_PATH):
        st.subheader("Interactive Network Map")
        with open(NETWORK_MAP_HTML_PATH, "r", encoding="utf-8") as f:
            components.html(f.read(), height=650, scrolling=True)

    if net_report and net_report.get("top_suspects"):
        st.subheader("Key Individuals Ranked by Network Influence")
        suspects_df = pd.DataFrame(net_report["top_suspects"])
        
        expected_cols = ["label", "risk_tier", "composite_score", "degree", "betweenness", "community_id"]
        for col in expected_cols:
            if col not in suspects_df.columns:
                suspects_df[col] = "N/A"
                
        df = suspects_df[expected_cols].rename(columns={
            "label": "Name", 
            "risk_tier": "Risk Tier", 
            "composite_score": "Influence Score",
            "degree": "Degree Centrality",
            "betweenness": "Betweenness Centrality",
            "community_id": "Community ID"
        })
        st.dataframe(df, use_container_width=True, hide_index=True)

    if intel_report and intel_report.get("alerts"):
        st.subheader("Suspicious Pattern Alerts")
        severity_filter = st.multiselect(
            "Filter by severity:", options=["critical", "high", "medium", "low"],
            default=["critical", "high"]
        )
        for a in intel_report["alerts"]:
            if a["severity"] not in severity_filter:
                continue
            label = f"[{a['severity'].upper()}] {a['alert_type']} (score {a['score']})"
            if a["severity"] in ("critical", "high"):
                st.error(f"**{label}**  \n{a['summary']}")
            else:
                st.warning(f"**{label}**  \n{a['summary']}")

if __name__ == "__main__":
    st.set_page_config(page_title="Investigation Intelligence Suite", layout="wide")
    tab1, tab2 = st.tabs(["Case Timeline", "Network & Intelligence"])
    with tab1:
        render_timeline_page()
    with tab2:
        render_network_intelligence_page()
