import json
import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components

# ==========================================
# TIMELINE ENGINE & MULTI-FILE INGESTION LOGIC
# ==========================================

class TimelineCorrelationEngine:
    """
    Ingests and transforms data from .csv and .txt output files generated by
    main_investigation_pipeline.py into chronologically structured timelines.
    """

    EVENT_COLOR_MAP = {
        "Occurrence": "#EF4444",      # Crimson / Incident Occurrence
        "FIR Report": "#F59E0B",      # Amber / Reporting Time
        "Call": "#3B82F6",            # Blue / CDR Traffic
        "FASTag / Vehicle": "#10B981", # Green / Toll & ANPR
        "Bank Transaction": "#8B5CF6", # Purple / Financial Log
        "Crypto": "#EC4899",          # Pink / Crypto Off-Ramp
        "Anomaly Alert": "#DC2626"    # Red Alert / Fraud & Mismatch
    }

    @classmethod
    def load_pipeline_data(cls) -> Dict[str, Any]:
        """Loads available CSV and TXT files generated by main_investigation_pipeline.py."""
        data = {}

        # CSV files generated by the pipeline
        files_to_load = {
            "fir": "complete_fir_dataset.csv",
            "cdr": "Call_Recording.csv",
            "fastag": "FASTag_Toll_Logs.csv",
            "bank": "Bank_Statement_Records.csv",
            "crypto": "Crypto_OnChain_Transactions.csv"
        }

        for key, filepath in files_to_load.items():
            if os.path.exists(filepath):
                try:
                    data[key] = pd.read_csv(filepath)
                except Exception:
                    data[key] = pd.DataFrame()
            else:
                data[key] = pd.DataFrame()

        # Extract text report insights if present
        data["txt_anomalies"] = cls._parse_text_report("FINAL_GOVERNMENT_CASE_INVESTIGATION_REPORT.txt")
        return data

    @classmethod
    def _parse_text_report(cls, filepath: str) -> List[Dict[str, Any]]:
        """Parses anomalies and findings out of the generated .txt report."""
        if not os.path.exists(filepath):
            return []

        anomalies = []
        current_case = "UNKNOWN"

        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line_str = line.strip()
                if "1. FIR BASIC INFORMATION - CASE ID:" in line_str:
                    match = re.search(r"CASE ID:\s*(FIR/\d+/\d+|\w+)", line_str)
                    if match:
                        current_case = match.group(1)
                elif "SEVERITY:" in line_str:
                    anomalies.append({
                        "Case_ID": current_case,
                        "Details": line_str
                    })
        return anomalies

    @classmethod
    def build_case_timeline(cls, data_store: Dict[str, Any], selected_case_id: Optional[str] = None) -> pd.DataFrame:
        """
        Builds a combined timeline dataframe mapping events from Occurrence -> FIR Reporting -> CDR/Vehicle/Bank Logs.
        """
        events = []

        # 1. Map FIR Base Events (Occurrence & Reporting)
        fir_df = data_store.get("fir", pd.DataFrame())
        if not fir_df.empty:
            target_fir = fir_df if not selected_case_id else fir_df[fir_df["FIR_No"] == selected_case_id]
            for _, row in target_fir.iterrows():
                case_id = str(row.get("FIR_No", "N/A"))
                place_of_occ = str(row.get("Place_of_Occurrence", "Unknown"))
                ps_location = str(row.get("Police_Station", "Police Station"))

                # Occurrence Time Event
                report_dt_str = str(row.get("Date_Time_of_FIR", ""))
                try:
                    rep_dt = datetime.strptime(report_dt_str, "%Y-%m-%d %H:%M")
                except ValueError:
                    rep_dt = datetime.now()

                days_offset = int(row.get("Days_Offset_N", 0))
                occ_dt = rep_dt - pd.Timedelta(days=days_offset)

                events.append({
                    "Case_ID": case_id,
                    "DateTime": occ_dt,
                    "Date": occ_dt.strftime("%Y-%m-%d"),
                    "Time": occ_dt.strftime("%H:%M"),
                    "Event Type": "Occurrence",
                    "Person": str(row.get("Accused_Name_Alias", "Unknown Accused")),
                    "Location": place_of_occ,
                    "Description": f"Incident Occurrence: {row.get('Case_Type', 'Offense')} reported at {place_of_occ}.",
                    "Source": "FIR Occurrence Log",
                    "Risk Score": 90
                })

                # Time of Reporting Event
                events.append({
                    "Case_ID": case_id,
                    "DateTime": rep_dt,
                    "Date": rep_dt.strftime("%Y-%m-%d"),
                    "Time": rep_dt.strftime("%H:%M"),
                    "Event Type": "FIR Report",
                    "Person": str(row.get("Informant_Name", "Complainant")),
                    "Location": ps_location,
                    "Description": f"FIR Registered at {ps_location} by {row.get('Informant_Name')}. Act: {row.get('Acts_Sections')}",
                    "Source": "FIR Filing Record",
                    "Risk Score": 50
                })

        # 2. Map Call Recording Data (CDR)
        cdr_df = data_store.get("cdr", pd.DataFrame())
        if not cdr_df.empty:
            target_cdr = cdr_df if not selected_case_id else cdr_df[cdr_df["Case_ID"] == selected_case_id]
            for _, row in target_cdr.head(100).iterrows(): # Sample top events for visual performance
                try:
                    c_dt = datetime.strptime(str(row.get("Call Date & Time")), "%d/%m/%Y %H:%M")
                except Exception:
                    continue

                events.append({
                    "Case_ID": str(row.get("Case_ID")),
                    "DateTime": c_dt,
                    "Date": c_dt.strftime("%Y-%m-%d"),
                    "Time": c_dt.strftime("%H:%M"),
                    "Event Type": "Call",
                    "Person": str(row.get("Calling Number (A-Party)")),
                    "Location": str(row.get("First Tower Location", "Cell Tower")),
                    "Description": f"Call to {row.get('Called Number (B-Party)')} ({row.get('Duration (s)')}s)",
                    "Source": "CDR Logs",
                    "Risk Score": 65 if int(row.get("Duration (s)", 0)) < 10 else 30
                })

        # 3. Map FASTag & Vehicle Logs
        fastag_df = data_store.get("fastag", pd.DataFrame())
        if not fastag_df.empty:
            target_fastag = fastag_df if not selected_case_id else fastag_df[fastag_df["Case_ID"] == selected_case_id]
            for _, row in target_fastag.iterrows():
                try:
                    v_dt = datetime.strptime(str(row.get("Timestamp (IST)")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                is_mismatch = str(row.get("ANPR Cross-Match")) == "MISMATCH"
                events.append({
                    "Case_ID": str(row.get("Case_ID")),
                    "DateTime": v_dt,
                    "Date": v_dt.strftime("%Y-%m-%d"),
                    "Time": v_dt.strftime("%H:%M"),
                    "Event Type": "Anomaly Alert" if is_mismatch else "FASTag / Vehicle",
                    "Person": str(row.get("Vehicle Registration")),
                    "Location": str(row.get("Toll Plaza ID & Location")),
                    "Description": f"Vehicle crossed toll plaza. Status: {row.get('Txn Status')}",
                    "Source": "FASTag/ANPR Feed",
                    "Risk Score": 95 if is_mismatch else 40
                })

        # 4. Map Bank Transactions
        bank_df = data_store.get("bank", pd.DataFrame())
        if not bank_df.empty:
            target_bank = bank_df if not selected_case_id else bank_df[bank_df["Case_ID"] == selected_case_id]
            for _, row in target_bank.iterrows():
                try:
                    b_dt = datetime.strptime(str(row.get("Transaction_DateTime")), "%Y-%m-%d %H:%M:%S")
                except Exception:
                    continue

                events.append({
                    "Case_ID": str(row.get("Case_ID")),
                    "DateTime": b_dt,
                    "Date": b_dt.strftime("%Y-%m-%d"),
                    "Time": b_dt.strftime("%H:%M"),
                    "Event Type": "Bank Transaction",
                    "Person": str(row.get("Person")),
                    "Location": "Banking System",
                    "Description": f"{row.get('Type_CR_DR')} Rs.{row.get('Amount_INR')} via {row.get('Channel')}",
                    "Source": "Bank Statements",
                    "Risk Score": 70
                })

        if not events:
            return pd.DataFrame()

        df = pd.DataFrame(events)
        df["DateTime"] = pd.to_datetime(df["DateTime"])
        return df.sort_values("DateTime")


# ==========================================
# STREAMLIT UI RENDERER: TIMELINE PAGE
# ==========================================

def render_timeline_page():
    st.markdown("## Multi-Source Case Timeline Analysis")
    st.caption("Extracted automatically from CSV logs and TXT investigation summaries generated by main_investigation_pipeline.py")

    # Load Pipeline Output Data
    data_store = TimelineCorrelationEngine.load_pipeline_data()
    fir_df = data_store.get("fir", pd.DataFrame())

    if fir_df.empty:
        st.warning("No CSV data found. Please run `python main_investigation_pipeline.py` first to generate dataset files.")
        return

    # Case Selection Filter
    available_cases = ["All Cases"] + list(fir_df["FIR_No"].unique())
    selected_case = st.selectbox("Select Specific Case ID to Inspect:", options=available_cases)

    case_filter = None if selected_case == "All Cases" else selected_case

    # Build Timeline DataFrame
    timeline_df = TimelineCorrelationEngine.build_case_timeline(data_store, selected_case_id=case_filter)

    if timeline_df.empty:
        st.info("No correlated timeline events available for this selection.")
        return

    # Sidebar Filter Controls
    st.sidebar.markdown("### Filter Timeline View")
    event_types = list(timeline_df["Event Type"].unique())
    selected_types = st.sidebar.multiselect("Event Types:", options=event_types, default=event_types)

    filtered_df = timeline_df[timeline_df["Event Type"].isin(selected_types)]

    # 1. Chronological Timeline Visualization Chart
    st.subheader("Interactive Multi-Event Chronology Chart")

    fig = px.scatter(
        filtered_df,
        x="DateTime",
        y="Person",
        color="Event Type",
        size="Risk Score",
        hover_data={"Case_ID": True, "Location": True, "Description": True, "Source": True, "Risk Score": True},
        color_discrete_map=TimelineCorrelationEngine.EVENT_COLOR_MAP,
        title=f"Incident Timeline & Sequence ({selected_case})"
    )

    fig.update_traces(marker=dict(symbol="circle", line=dict(width=1, color="DarkSlateGrey")))
    fig.update_layout(
        xaxis_title="Timeline (Time of Occurrence → Reporting → Events)",
        yaxis_title="Entity / Involved Person / Vehicle",
        height=450,
        template="plotly_dark"
    )

    st.plotly_chart(fig, use_container_width=True)

    # 2. Case Summary Metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Extracted Events", len(filtered_df))
    c2.metric("Involved Entities", filtered_df["Person"].nunique())
    c3.metric("Primary Location", filtered_df["Location"].mode()[0] if not filtered_df.empty else "N/A")
    c4.metric("Max Risk Score", f"{filtered_df['Risk Score'].max() if not filtered_df.empty else 0}/100")

    # 3. Time Log & Incident Data Ledger Table
    st.subheader("Correlated Event Data Table")

    display_df = filtered_df[[
        "Case_ID", "Date", "Time", "Event Type", "Person",
        "Location", "Description", "Source", "Risk Score"
    ]].copy()

    st.dataframe(
        display_df,
        column_config={
            "Risk Score": st.column_config.ProgressColumn(
                "Risk Severity",
                format="%d",
                min_value=0,
                max_value=100
            )
        },
        use_container_width=True,
        hide_index=True
    )

    # 4. Text Report Anomaly Integration View
    txt_anomalies = data_store.get("txt_anomalies", [])
    if txt_anomalies:
        st.subheader("Automated Report Intelligence Flags (.txt Summary)")
        relevant_anomalies = [
            a for a in txt_anomalies if case_filter is None or a["Case_ID"] == case_filter
        ]
        if relevant_anomalies:
            for item in relevant_anomalies[:5]: # Show top 5 relevant flags
                st.error(f"**[{item['Case_ID']}]**: {item['Details']}")
        else:
            st.success("No automated report anomalies detected for this case.")

# ==========================================
# NETWORK & INTELLIGENCE PAGE (NEW)
# ==========================================
# Surfaces the output of the new sihrelationship.py / sihnetworkanalytics.py /
# sihintelligenceengine.py modules -- the "visual and analytical insights"
# and "key individuals / suspicious patterns" the problem statement asks
# for. Reads the JSON/HTML files those modules already write, so this page
# has no analysis logic of its own -- it's a pure viewer.

NETWORK_REPORT_PATH = "network_analytics_report.json"
INTELLIGENCE_REPORT_PATH = "intelligence_report.json"
NETWORK_MAP_HTML_PATH = "network_map.html"


def _load_json(path: str) -> Optional[Dict[str, Any]]:
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def render_network_intelligence_page():
    st.markdown("## Criminal Network & Intelligence Overview")
    st.caption("Generated by sihrelationship.py -> sihnetworkanalytics.py -> sihintelligenceengine.py")

    net_report = _load_json(NETWORK_REPORT_PATH)
    intel_report = _load_json(INTELLIGENCE_REPORT_PATH)

    if not net_report and not intel_report:
        st.warning(
            "No analysis output found. Run `python main_investigation_pipeline.py` "
            "(it now runs the analysis modules automatically), or run "
            "`python sihrelationship.py`, `python sihnetworkanalytics.py`, and "
            "`python sihintelligenceengine.py` in that order."
        )
        return

    # 1. Headline metrics
    if net_report:
        s = net_report["summary"]
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Entities (Nodes)", s.get("total_nodes", 0))
        c2.metric("Relationships (Edges)", s.get("total_edges", 0))
        c3.metric("Critical Bridges", s.get("critical_bridge_count", 0))
        c4.metric("Cells / Communities", s.get("total_communities", 0))

    if intel_report:
        m = intel_report["meta"]
        c1, c2 = st.columns(2)
        c1.metric("Intelligence Alerts", m.get("alert_count", 0))
        c2.metric("Critical / High Severity", m.get("critical_or_high_alerts", 0))

    # 2. Interactive network graph
    if os.path.exists(NETWORK_MAP_HTML_PATH):
        st.subheader("Interactive Network Map")
        with open(NETWORK_MAP_HTML_PATH, "r", encoding="utf-8") as f:
            components.html(f.read(), height=650, scrolling=True)

    # 3. Top suspects (key individuals -- problem statement ask)
    if net_report and net_report.get("top_suspects"):
        st.subheader("Key Individuals Ranked by Network Influence")
        suspects_df = pd.DataFrame(net_report["top_suspects"])
        
        # Ensure fallback defaults if columns are missing
        expected_cols = ["label", "risk_tier", "composite_score", "degree", "betweenness"]
        for col in expected_cols:
            if col not in suspects_df.columns:
                suspects_df[col] = "N/A"
                
        df = suspects_df[expected_cols].rename(columns={
            "label": "Name", 
            "risk_tier": "Risk Tier", 
            "composite_score": "Influence Score",
            "degree": "Degree Centrality",
            "betweenness": "Betweenness Centrality"
        })
        st.dataframe(df, use_container_width=True, hide_index=True)

    # 4. Intelligence alerts
    if intel_report and intel_report.get("alerts"):
        st.subheader("Suspicious Pattern Alerts")
        severity_filter = st.multiselect(
            "Filter by severity:", options=["critical", "high", "medium", "low"],
            default=["critical", "high"]
        )
        for a in intel_report["alerts"]:
            if a["severity"] not in severity_filter:
                continue
            label = f"[{a['severity'].upper()}] {a['alert_type']} (score {a['score']})"
            if a["severity"] in ("critical", "high"):
                st.error(f"**{label}**  \n{a['summary']}")
            else:
                st.warning(f"**{label}**  \n{a['summary']}")


# Standalone Execution Entry Point
if __name__ == "__main__":
    st.set_page_config(page_title="Investigation Intelligence Suite", layout="wide")
    tab1, tab2 = st.tabs(["Case Timeline", "Network & Intelligence"])
    with tab1:
        render_timeline_page()
    with tab2:
        render_network_intelligence_page()
